### ISSUE TITLE
Release version 0.1.5 - no more Engine enum

### ISSUE THREAD

**Issue by manuelzander** [deontologician/openai-api-rust#13]
👋🏼 Hi, I've been playing around with this crate and realised that the lastest released version is [0.1.4](https://crates.io/crates/openai-api/0.1.4).

Version [0.1.5-alpha.0](https://github.com/deontologician/openai-api-rust/pull/10) fixes an issue I have with the API, namely I would like to use the `davinci-instruct-beta` `engine`, which I think is possible with _version 0.1.5-alpha.0_, since that version doesn't rely on the `Engine` enum anymore.

Would it be possible to release version 0.1.5 on crates.io?

Many thanks,
manuel

**Comment by manuelzander** [comment]
In the meantime, specifying the below in the `Cargo.toml` of my project seems to allow me to run the [examples](https://github.com/deontologician/openai-api-rust/tree/main/examples).

```toml
[dependencies]
openai-api = { git = "https://github.com/deontologician/openai-api-rust" , branch = "main" }
tokio = { version = "^0.2.5", features = ["full"]}
```
